server:
  port: 9800
spring:
  application:
    name: zsh-zuul-sentinel
  cloud:
    sentinel:
      zuul:
        order:
          pre: 1000
          post: 1000
          error: -1
    nacos:
      config:
        server-addr: 172.22.122.21:8848
#        file-extension: yaml
#        namespace: DEFAULT_GROUP
#        endpoint: 172.22.122.21:8848
      discovery:
        server-addr: 172.22.122.21:8848
#  profiles:
#    active: dev
zuul:
  host:
    connect-timeout-millis: 20000 #HTTP超时
    socket-timeout-millis: 20000 #Socket超时
  strip-prefix: true
  add-host-header: true
  routes:
    zsh-proxy-baidu:
      path: /zsh/baidu/**         # curl localhost:9800/zsh/baidu 带后缀则成为path-parameter
      url: http://localhost:9800/get
#  include-debug-header: true
#  ignored-services:
#    - xxx
#    - xxx
    zsh-example-service:
      path: /get/**
      service-id: zsh-zuul-sentinel-2

logging:
  level:
    root: INFO

