server:
  port: 9800
spring:
  application:
    name: zsh-pure-zuul-gateway
  cloud:
    sentinel:
      zuul:
        order:
          pre: 1000
          post: 1000
          error: -1
#--------------------------------------------------------------------
zuul:
  host:
    socket-timeout-millis:  20000 #Socket超时
    connect-timeout-millis: 20000 #HTTP超时
  strip-prefix: true
  add-host-header: true
  # 路由参数
  routes:
    zsh-example-service:
      path: /rrr/**
      service-id: zsh-nacos-producer
      # zuul默认会过滤以下header，因此设置一个不会使用的header覆盖默认设置，确保敏感Header可以传递到下一个服务
      # Authorization、Set-Cookie、Cookie、Host、Connection、Content-Length、Content-Encoding、Server、Transfer-Encoding、X-Application-Context
      sensitive-headers: Not-Existing-Header
#--------------------------------------------------------------------
#下游服务负载均衡超时配置
zsh-nacos-producer:
  ribbon:
    ReadTimeout: 4000
    ConnectTimeout: 2000
#    MaxAutoRetries: 0
#    MaxAutoRetriesNextServer: 0  #默认寻找下一个负载服务重试一次
hystrix:
  metrics:
    enabled: false
  command:
    #default: #默认为default全局生效
    zsh-nacos-producer:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
#--------------------------------------------------------------------
feign:
  sentinel:
    enabled: true
#logging:
#  level:
#    root: DEBUG
#  file:
#    path: info.log

#zuul:
#  routes:
#    echo:
#      path: /myusers/**
#      serviceId: myusers-service
#      stripPrefix: true
#
#hystrix:
#  command:
#    myusers-service:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: ...ge
#
#myusers-service:
#  ribbon:
#    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
#    listOfServers: https://example1.com,http://example2.com
#    ConnectTimeout: 1000
#    ReadTimeout: 3000
#    MaxTotalHttpConnections: 500
#    MaxConnectionsPerHost: 100
zsh:
  springboot:
    template:
      custom:
        key : val