server:
  port: 7089
  undertow:
    #    io-threads: 4         # 设置IO线程数, 它主要执 行? 非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核 心 一个线程
    #    worker-threads: 600   # 阻塞任务线程池, 当执 行?类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    buffer-size: 2048     # 每块buffer的空间 大 小,越 小的空间被利? 用越充分，块多了?但是会变慢
    direct-buffers: true  # 是否分配的直接内存

curator:
  retryCount: 5
  elapsedTimeMs: 5000
  connectString: 106.54.211.146:2181
  sessionTimeoutMs: 60000
  connectionTimeoutMs: 10000
