spring:
  profiles:
    active: sharding-tables-precise-algorithm
mybatis-plus:
  mapper-locations: classpath*:zsh/springboot/shardingjdbcmybatisplus/ds/mapper/**/*Mapper.xml
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl