spring:
  application:
    name: cacheable-application
  profiles:
    active: l2
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: cacheable-application